# Generated by Django 6.0.4 on 2026-05-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockActual',
            fields=[
                ('producto_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50)),
                ('producto', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('stock_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alerta_stock', models.BooleanField()),
            ],
            options={
                'db_table': 'vw_stock_actual',
                'managed': False,
            },
        ),
    ]
